// <auto-generated />
using System;
using ClassLibrary.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassLibrary.Migrations
{
    [DbContext(typeof(TeamDbContext))]
    [Migration("20240128183242_SeedGroupes")]
    partial class SeedGroupes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ActivityProfile", b =>
                {
                    b.Property<int>("Activitiesid")
                        .HasColumnType("int");

                    b.Property<int>("Profilesid")
                        .HasColumnType("int");

                    b.HasKey("Activitiesid", "Profilesid");

                    b.HasIndex("Profilesid");

                    b.ToTable("ActivityProfile");
                });

            modelBuilder.Entity("ClassLibrary.Db.Activity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Age_rating")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Time_end")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Time_start")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isPrivate")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Age_rating = "All Ages",
                            Description = "A fun and competitive football match.",
                            Name = "Football Match",
                            Time_end = new DateTime(2024, 1, 28, 12, 32, 41, 655, DateTimeKind.Local).AddTicks(2475),
                            Time_start = new DateTime(2024, 1, 28, 10, 32, 41, 655, DateTimeKind.Local).AddTicks(2429),
                            isPrivate = false
                        },
                        new
                        {
                            id = 2,
                            Age_rating = "12+",
                            Description = "Training session for local basketball team.",
                            Name = "Basketball Training",
                            Time_end = new DateTime(2024, 1, 28, 13, 32, 41, 655, DateTimeKind.Local).AddTicks(2492),
                            Time_start = new DateTime(2024, 1, 28, 11, 32, 41, 655, DateTimeKind.Local).AddTicks(2490),
                            isPrivate = true
                        },
                        new
                        {
                            id = 3,
                            Age_rating = "All Ages",
                            Description = "Regional chess tournament open for all.",
                            Name = "Chess Tournament",
                            Time_end = new DateTime(2024, 1, 29, 14, 32, 41, 655, DateTimeKind.Local).AddTicks(2499),
                            Time_start = new DateTime(2024, 1, 29, 10, 32, 41, 655, DateTimeKind.Local).AddTicks(2496),
                            isPrivate = false
                        },
                        new
                        {
                            id = 4,
                            Age_rating = "18+",
                            Description = "Discussing the latest in literary wonders.",
                            Name = "Book Club",
                            Time_end = new DateTime(2024, 1, 30, 12, 32, 41, 655, DateTimeKind.Local).AddTicks(2507),
                            Time_start = new DateTime(2024, 1, 30, 10, 32, 41, 655, DateTimeKind.Local).AddTicks(2505),
                            isPrivate = false
                        },
                        new
                        {
                            id = 5,
                            Age_rating = "16+",
                            Description = "A relaxing yoga session to improve your flexibility.",
                            Name = "Yoga Class",
                            Time_end = new DateTime(2024, 1, 28, 13, 32, 41, 655, DateTimeKind.Local).AddTicks(2513),
                            Time_start = new DateTime(2024, 1, 28, 12, 32, 41, 655, DateTimeKind.Local).AddTicks(2511),
                            isPrivate = true
                        },
                        new
                        {
                            id = 6,
                            Age_rating = "All Ages",
                            Description = "Learn to cook Italian cuisine with expert chefs.",
                            Name = "Cooking Workshop",
                            Time_end = new DateTime(2024, 1, 31, 15, 32, 41, 655, DateTimeKind.Local).AddTicks(2521),
                            Time_start = new DateTime(2024, 1, 31, 10, 32, 41, 655, DateTimeKind.Local).AddTicks(2519),
                            isPrivate = false
                        },
                        new
                        {
                            id = 7,
                            Age_rating = "18+",
                            Description = "Collaborative event to solve programming challenges.",
                            Name = "Coding Hackathon",
                            Time_end = new DateTime(2024, 2, 2, 10, 32, 41, 655, DateTimeKind.Local).AddTicks(2527),
                            Time_start = new DateTime(2024, 2, 1, 10, 32, 41, 655, DateTimeKind.Local).AddTicks(2525),
                            isPrivate = false
                        },
                        new
                        {
                            id = 8,
                            Age_rating = "12+",
                            Description = "Experience the thrill of rock climbing with trained instructors.",
                            Name = "Rock Climbing Adventure",
                            Time_end = new DateTime(2024, 1, 29, 16, 32, 41, 655, DateTimeKind.Local).AddTicks(2533),
                            Time_start = new DateTime(2024, 1, 29, 12, 32, 41, 655, DateTimeKind.Local).AddTicks(2531),
                            isPrivate = true
                        },
                        new
                        {
                            id = 9,
                            Age_rating = "All Ages",
                            Description = "Beginner guitar lessons for aspiring musicians.",
                            Name = "Guitar Lessons",
                            Time_end = new DateTime(2024, 1, 30, 13, 32, 41, 655, DateTimeKind.Local).AddTicks(2539),
                            Time_start = new DateTime(2024, 1, 30, 11, 32, 41, 655, DateTimeKind.Local).AddTicks(2537),
                            isPrivate = true
                        },
                        new
                        {
                            id = 10,
                            Age_rating = "All Ages",
                            Description = "Showcasing contemporary art from local artists.",
                            Name = "Art Exhibition",
                            Time_end = new DateTime(2024, 2, 3, 18, 32, 41, 655, DateTimeKind.Local).AddTicks(2546),
                            Time_start = new DateTime(2024, 2, 3, 10, 32, 41, 655, DateTimeKind.Local).AddTicks(2544),
                            isPrivate = false
                        });
                });

            modelBuilder.Entity("ClassLibrary.Db.Group", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReqNumUsers")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            id = 1,
                            About = "We are a group1",
                            ActivityId = 1,
                            Name = "Group1",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 2,
                            About = "We are a group2",
                            ActivityId = 1,
                            Name = "Group2",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 3,
                            About = "We are a group3",
                            ActivityId = 2,
                            Name = "Group3",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 4,
                            About = "We are a group4",
                            ActivityId = 2,
                            Name = "Group4",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 5,
                            About = "We are a group5",
                            ActivityId = 3,
                            Name = "Group5",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 6,
                            About = "We are a group6",
                            ActivityId = 3,
                            Name = "Group6",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 7,
                            About = "We are a group7",
                            ActivityId = 4,
                            Name = "Group7",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 8,
                            About = "We are a group8",
                            ActivityId = 4,
                            Name = "Group8",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 9,
                            About = "We are a group9",
                            ActivityId = 5,
                            Name = "Group9",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 10,
                            About = "We are a group10",
                            ActivityId = 5,
                            Name = "Group10",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 11,
                            About = "We are a group11",
                            ActivityId = 6,
                            Name = "Group11",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 12,
                            About = "We are a group12",
                            ActivityId = 6,
                            Name = "Group12",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 13,
                            About = "We are a group13",
                            ActivityId = 7,
                            Name = "Group13",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 14,
                            About = "We are a group14",
                            ActivityId = 7,
                            Name = "Group14",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 15,
                            About = "We are a group15",
                            ActivityId = 8,
                            Name = "Group15",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 16,
                            About = "We are a group16",
                            ActivityId = 8,
                            Name = "Group16",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 17,
                            About = "We are a group17",
                            ActivityId = 9,
                            Name = "Group17",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 18,
                            About = "We are a group18",
                            ActivityId = 9,
                            Name = "Group18",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 19,
                            About = "We are a group19",
                            ActivityId = 10,
                            Name = "Group19",
                            ReqNumUsers = 10
                        },
                        new
                        {
                            id = 20,
                            About = "We are a group20",
                            ActivityId = 10,
                            Name = "Group20",
                            ReqNumUsers = 10
                        });
                });

            modelBuilder.Entity("ClassLibrary.Db.InterestTag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Profileid")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Profileid");

                    b.ToTable("InterestTags");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Tag = "Football"
                        },
                        new
                        {
                            id = 2,
                            Tag = "Basketball"
                        },
                        new
                        {
                            id = 3,
                            Tag = "Soccer"
                        },
                        new
                        {
                            id = 4,
                            Tag = "Hiking"
                        },
                        new
                        {
                            id = 5,
                            Tag = "Running"
                        });
                });

            modelBuilder.Entity("ClassLibrary.Db.Profile", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AboutMe")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("Image")
                        .HasColumnType("blob");

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LookingFor")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pronouns")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            AboutMe = "I am a student at the University of Utah",
                            Image = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            Links = "https://www.facebook.com/ https://www.instagram.com/",
                            LookingFor = "I am looking for a group of people to play football with",
                            Name = "Football",
                            Pronouns = "He/Him",
                            UserId = 1
                        },
                        new
                        {
                            id = 2,
                            AboutMe = "I am a student at the University of Utah",
                            Links = "https://www.facebook.com/ https://www.instagram.com/",
                            LookingFor = "I am looking for a group of people to play basketball with",
                            Name = "Basketball",
                            Pronouns = "He/Him",
                            UserId = 1
                        },
                        new
                        {
                            id = 3,
                            AboutMe = "I am a student at the University of Utah",
                            Image = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
                            Links = "https://www.facebook.com/ https://www.instagram.com/",
                            LookingFor = "I am looking for a group of people to play football with",
                            Name = "Football",
                            Pronouns = "He/Him",
                            UserId = 2
                        },
                        new
                        {
                            id = 4,
                            AboutMe = "I am a student at the University of Utah",
                            Links = "https://www.facebook.com/ https://www.instagram.com/",
                            LookingFor = "I am looking for a group of people to play basketball with",
                            Name = "Basketball",
                            Pronouns = "He/Him",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ClassLibrary.Db.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Groupid")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Groupid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            BDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jd@gmail.com",
                            Name = "John Doe",
                            Nickname = "JD",
                            Password = "password"
                        },
                        new
                        {
                            id = 2,
                            BDate = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane@gmai.com",
                            Name = "Jane Doe",
                            Nickname = "Jane",
                            Password = "password"
                        });
                });

            modelBuilder.Entity("GroupProfile", b =>
                {
                    b.Property<int>("Groupsid")
                        .HasColumnType("int");

                    b.Property<int>("Profilesid")
                        .HasColumnType("int");

                    b.HasKey("Groupsid", "Profilesid");

                    b.HasIndex("Profilesid");

                    b.ToTable("GroupProfile");
                });

            modelBuilder.Entity("ActivityProfile", b =>
                {
                    b.HasOne("ClassLibrary.Db.Activity", null)
                        .WithMany()
                        .HasForeignKey("Activitiesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLibrary.Db.Profile", null)
                        .WithMany()
                        .HasForeignKey("Profilesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassLibrary.Db.Group", b =>
                {
                    b.HasOne("ClassLibrary.Db.Activity", "Activity")
                        .WithMany("Groups")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("ClassLibrary.Db.InterestTag", b =>
                {
                    b.HasOne("ClassLibrary.Db.Profile", null)
                        .WithMany("InterestTags")
                        .HasForeignKey("Profileid");
                });

            modelBuilder.Entity("ClassLibrary.Db.Profile", b =>
                {
                    b.HasOne("ClassLibrary.Db.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassLibrary.Db.User", b =>
                {
                    b.HasOne("ClassLibrary.Db.Group", null)
                        .WithMany("Users")
                        .HasForeignKey("Groupid");
                });

            modelBuilder.Entity("GroupProfile", b =>
                {
                    b.HasOne("ClassLibrary.Db.Group", null)
                        .WithMany()
                        .HasForeignKey("Groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClassLibrary.Db.Profile", null)
                        .WithMany()
                        .HasForeignKey("Profilesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassLibrary.Db.Activity", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("ClassLibrary.Db.Group", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClassLibrary.Db.Profile", b =>
                {
                    b.Navigation("InterestTags");
                });
#pragma warning restore 612, 618
        }
    }
}
